---
- name: Converge
  hosts: all

  vars:
    cntp_ntp_service_enable: false

  tasks:
    - name: "Include ansible-role-configure_ntp"
      include_role:
        name: "ansible-role-configure_ntp"
