---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '35 2 * * *'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos8
        tag:
          - latest
    steps:
      - name: Check out git repository.
        uses: actions/checkout@v2

      - name: Setup python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install package dependencies.
        run: pip3 install ansible docker molecule[docker]

      - name: Perform molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_TAG: ${{ matrix.tag }}
